services:
  parity:
    image: ethcore/parity:stable
    hostname: parity
    net: "dev"
    publish: ["8080:8080", "8545:8545", "8180:8180", "30303:30303"]
    tty: true
    rm: true
    interactive: true
    volume: ["parity:/mnt"]
    command: "--config=/mnt/config.toml"

networks:
  dev:
