[parity]
chain = "/root/.local/share/io.parity.ethereum/carchain-chainspec.json"

[network]
warp = true

[ui]
force = false
disable = false
port = 8181
interface = "0.0.0.0"

[rpc]
disable = false
port = 8546
interface = "0.0.0.0"
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_accounts", "parity_set", "signer", "traces", "rpc"]

[dapps]
disable = false
port = 8081
interface = "0.0.0.0"
hosts = ["all"]

[account]
password = ["/root/.local/share/io.parity.ethereum/validator.pwds"]
[mining]
engine_signer = "0x00d409ec80bce3a94366ceb50007bf482bec1d08"
reseal_on_txs = "none"
