[parity]
base_path = "/mnt"
chain = "ropsten"

[network]
warp = true

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
hosts = ["all"]

[dapps]
disable = false
port = 8080
interface = "0.0.0.0"
hosts = ["all"]
